rag:
  # -- Enable RAG
  # ref: https://docs.openwebui.com/getting-started/env-configuration#retrieval-augmented-generation-rag
  enabled: true
  vectorDB: milvus
  embeddingEngine: ""
  embeddingModel: ""

milvus:
  # -- Enable Milvus installation. Deploys a Milvus cluster/standalone with subchart 'milvus' from zilliztech
  # ref: https://github.com/zilliztech/milvus-helm/tree/master/charts/milvus
  enabled: true
  uri: "http://open-webui-milvus:19530"
  db: default
  token: {}
  cluster:
    enabled: false # This means that the Milvus runs with standalone mode
  minio:
    enabled: true
    resources:
      requests:
        memory: 50Mi
    persistence:
      enabled: true
      size: 1Gi
  etcd:
    enabled: true
  pulsar:
    enabled: false
  pulsarv3:
    enabled: false
  kafka:
    enabled: false
  externalS3:
    enabled: false
  externalEtcd:
    enabled: false

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health/db
    port: http
startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30 # Adjust this value according to the startup time of the application
  periodSeconds: 10 # Adjust this value according to the startup time of the application
  failureThreshold: 20 # Adjust this value according to the startup time of the application
