{{- range .Values.issuers }}
---
# raw issuer: {{ . | toJson }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
apiVersion: cert-manager.io/v1
kind: Issuer
{{ template "cert-manager-issuers.metadata" (dict "data" . "root" $) }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
