apiVersion: v2
appVersion: 1.0.1
dependencies:
- condition: ingress.nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 14.1.3
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.14.0
description: A helm chart to deploy Infisical
name: infisical-standalone
type: application
version: 1.4.0
