apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-stack
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: develop
    path: helm/argo-cd-stack-0.0.2
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        argo-cd:
          enabled: true
          configs:
            secret:
              argocdServerAdminPassword: "$2a$10$90zWm98rCpY2pZSwbV4Eg.4WzpgLDZbe3tdQK25ZIyCGtxmgjFxl6"
        argocd-apps:
          enabled: true
          projects:
            base:
              clusterResourceWhitelist:
                - group: '*'
                  kind: '*'
              destinations:
                - namespace: '*'
                  server: 'https://kubernetes.default.svc'
              sourceRepos:
                - '*'
        argocd-image-updater:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
