---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/cert-manager/cert-manager-v1.16.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        crds:
          enabled: true
          keep: true
        extraResources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: nginx-letsencrypt-stag
            spec:
              acme:
                email: jyjeon@outlook.com
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: nginx-letsencrypt-stag
                solvers:
                  - http01:
                      ingress:
                        ingressClassName: nginx
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: nginx-letsencrypt-prod
            spec:
              acme:
                email: jyjeon@outlook.com
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: nginx-letsencrypt-prod
                solvers:
                  - http01:
                      ingress:
                        ingressClassName: nginx
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: istio-letsencrypt-stag
            spec:
              acme:
                email: jyjeon@outlook.com
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: istio-letsencrypt-stag
                solvers:
                  - http01:
                      ingress:
                        ingressClassName: istio
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: istio-letsencrypt-prod
            spec:
              acme:
                email: jyjeon@outlook.com
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: istio-letsencrypt-prod
                solvers:
                  - http01:
                      ingress:
                        ingressClassName: istio
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
