apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  project: default
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/cloudflare/cloudflare-tunnel-remote-0.1.2-custom
    helm:
      valuesObject:
        replicaCount: 2
        cloudflare:
          secretName: cloudflared-credentials
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: cloudflared-credentials
            spec:
              encryptedData:
                tunnelToken: AgAV9KuUKnjp5ni+bE1g9ucrRgQqUdYMBXcpnV9pk4ePH0euiNTIAR313ARC6RFdmCJxgwWiVPr+s1Se4Ugz9wR9pBzlfHhTbw5i4aTqCmzrkCDuWNvhvIWpXmRXH6IcyxHytbRur0xiy8f2Vd3XvXFiuJXqpMLE2ismTcYExV4QX8sK+IRI1H0uP5rqx28oZdQSAe6BBYsAUSro5ldPkkuRaeprZmiqytjtmjjdjze2Y3xgoNQpPb0hujC4LyvAz/XB4ehFSdSFWZRh7OErMyi9htjxoobZpD131UKfN7p9uehCh0zXOndtE+5fKRakLBDxHSFonzuFIl/UdGZdkP0EWulqtE643vdNCLmDHonWhwMEn4nZ6FsOUTQVHXwWVsPoILtjheDsE7JIrAam52UADeyw+jJm1ntmxwDLW5+alNqZURKdHiw7t8oIOYy9piJBnyKbUg7V/iZs1LLgiA2PSk4M8epiH1p4eZJHiZOL6KdqcbcsxVef20NWXl2ngiFfJ6A9B6KY9vcdxK9rJEANjCOUCtYCc9owH3wof+1C2y7NiCnC2n5k4FW5aGSOwQpuRC0rELdgFAiZZPRipcuNMlErSqK/TzPaXveI9KCdkwstfrAtT91xo4LncXSDyBVCsaBPBpkvC3U0vhtGZDm+yiKpqQePQtJABhIHMvljg+Cg7YGYJOzrl8VMoOF/8h1BA1/98H2+nyhQWWUBgkbQsvEIcFZ2L0pu0bXa7FYoTT2stjcpx7aPN4lO7WEK++3c11VHrDxqAX0t3BhkVOT7hMJqV8gWWd8bexAI1y9ufbc9bfD+xtDpb2v59zSdWRMoiAlHCVt8cUx6GTUmMbovG5jdVuGxeuK8ILCLoK5OaPyzA9mIQoyJI50Wd03Q05jmGNRUlLrxchwb03r5Ij0WveBmnVG7oTc0/AozJqzItH9NzsqHaahw
              template:
                metadata:
                  name: cloudflared-credentials
                type: Opaque
  destination:
    namespace: cloudflare
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
