apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-operator
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: develop
    path: helm/etcd-operator-v0.4.1
    helm:
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: etcd-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
