---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/gateway-api/gateway-api-1.2.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
