apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: develop
    path: helm/gpu-operator-v24.6.2
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        operator:
          defaultRuntime: containerd
        validator:
          driver:
            env:
              - name: DISABLE_DEV_CHAR_SYMLINK_CREATION
                value: "true"
        driver:
          enabled: false
        toolkit:
          env:
          - name: CONTAINERD_CONFIG
            value: /var/snap/microk8s/current/args/containerd-template.toml
          - name: CONTAINERD_SOCKET
            value: /var/snap/microk8s/common/run/containerd.sock
          - name: CONTAINERD_RUNTIME_CLASS
            value: nvidia
          - name: CONTAINERD_SET_AS_DEFAULT
            value: "true"
        migManager:
          enabled: false
        nodeStatusExporter:
          enabled: false
        node-feature-discovery:
          worker:
            nodeSelector:
              node-role.kubernetes.io/gpu: ""
  destination:
    namespace: gpu-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
