apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/homer-k8s-0.3.5-jyje
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        fullnameOverride: homer
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: homer.app.jyje.online
              paths:
                - service:
                    name: homer
                    port: 8080
                  path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: homer-letsencrypt-tls
              hosts:
                - homer.app.jyje.online
        homer:
          image:
            repository: b4bz/homer
            tag: v25.03.1              
  destination:
    namespace: homer-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
