apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/homer-alpha0.0.2
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        defaultPodOptions:
          hostIPC: {}
          hostNetwork: {}
          hostPID: {}
        controllers:
          main:
            type: deployment
            replicas: 2
            strategy: RollingUpdate
            rollingUpdate:
              surge: 25%
              unavailable: "0"
            initContainers:
              get-assets:
                image:
                  repository: alpine/git
                  tag: latest
                  imagePullPolicy: Always
                command: [sh, -c]
                args: |
                  git clone -b jyje https://github.com/jyje/homer.git /repo &&
                  find /repo/public/assets/ \
                    -type f \
                    -name "*.dist" \
                    -exec rm {} \; &&
                  cp -r /repo/public/assets/* /www/assets/
            containers:
              main:
                image:
                  repository: b4bz/homer
                  tag: v24.12.1
                  pullPolicy: Always
                env:
                  - name: TZ
                    value: Seoul/Asia
                ports:
                  - name: http
                    protocol: TCP
                    port: 8080
                    containerPort: 8080
                probes:
                  liveness:
                    spec:
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness:
                    spec:
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  startup:
                    spec:
                      initialDelaySeconds: 0
                      timeoutSeconds: 1
                      periodSeconds: 5
                      failureThreshold: 3
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1000
                  runAsGroup: 1000
        service:
          main:
            type: ClusterIP
            ports:
              http:
                port: 8080
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: app.jyje.live
                paths:
                  - service:
                      name: homer
                      port: 8080
                    path: /
            tls:
              - hosts:
                  - app.jyje.live
                secretName: app-letsencrypt-tls
        persistence:
          assets:
            enabled: true
            type: emptyDir
            globalMounts:
            - path: /www/assets          
  destination:
    namespace: homer
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
