---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio/gateway-1.29.0
    helm:
      valuesObject:
        extraResources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: istio-gateway
              labels:
                istio-injection: enabled
          - apiVersion: networking.k8s.io/v1
            kind: IngressClass
            metadata:
              name: istio
            spec:
              controller: istio.io/ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-gateway
  syncPolicy:
    automated: {}
