# Istio Ambient mode via Helm (https://istio.io/latest/docs/ambient/install/helm/)
# Using local Helm charts from this repo (helm/istio-*).
# Gateway API CRDs (if using Gateway API): kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml
---
# Ignore drift: istiod patches these webhooks at runtime (e.g. istiod-default-validator: failurePolicy→Fail, caBundle).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio-base-1.28.3
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
---
# Ignore drift: istiod updates webhooks at runtime (failurePolicy, clientConfig.caBundle).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio-istiod-1.28.3
    helm:
      valuesObject:
        profile: ambient
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
        - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio-cni-1.28.3
    helm:
      valuesObject:
        profile: ambient
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio-ztunnel-1.28.3
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: {}
