---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/istio/gateway-1.29.0
    helm:
      valuesObject:
        resources:
          limits:
            memory: 2048Mi
        extraResources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: istio-gateway
              labels:
                istio-injection: enabled
          - apiVersion: networking.k8s.io/v1
            kind: IngressClass
            metadata:
              name: istio
            spec:
              controller: istio.io/ingress-controller
          - apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: homer-gateway-tls
              namespace: istio-gateway
            spec:
              secretName: homer-gateway-tls
              issuerRef:
                name: istio-letsencrypt-prod
                kind: ClusterIssuer
              dnsNames:
                - homer.app.jyje.online
          - apiVersion: gateway.networking.k8s.io/v1
            kind: Gateway
            metadata:
              name: istio-gateway
              namespace: istio-gateway
            spec:
              gatewayClassName: istio
              listeners:
                - name: http
                  port: 80
                  protocol: HTTP
                  allowedRoutes:
                    namespaces:
                      from: All
                - name: https-homer
                  port: 443
                  protocol: HTTPS
                  hostname: homer.app.jyje.online
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - kind: Secret
                        name: homer-gateway-tls
                  allowedRoutes:
                    namespaces:
                      from: All
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-gateway
  syncPolicy:
    automated: {}
