apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/grafana/loki-7.0.0
    helm:
      valuesObject:
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

        sidecar:
          rules:
            enabled: false

        singleBinary:
          replicas: 1
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: loki
                    topologyKey: kubernetes.io/hostname
          persistence:
            enabled: true
            storageClass: subdir-usb
            size: 10Gi

        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
