apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/longhorn-1.8.1
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        global:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
        persistence:
          defaultClassReplicaCount: 2
        preUpgradeChecker:
          jobEnabled: false
        csi:
          kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
        defaultSettings:
          defaultDataPath: longhorn
          guaranteedInstanceManagerCPU: 1
          taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
        longhornUI:
          replicas: 1
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
