apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/longhorn-1.10.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        # global:
        #   tolerations:
        #     - key: "node-role.kubernetes.io/control-plane"
        #       operator: "Exists"
        #       effect: "NoSchedule"
        persistence:
          defaultClassReplicaCount: 2
          defaultDataLocality: best-effort
        preUpgradeChecker:
          jobEnabled: false
        csi:
          kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
        defaultSettings:
          # taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
          autoSalvage: false
          defaultDataPath: longhorn
          guaranteedInstanceManagerCPU: 1
          defaultReplicaCount: 2
          replicaReplenishmentWaitInterval: 600
          concurrentReplicaRebuildPerNodeLimit: 1
          concurrentVolumeBackupRestorePerNodeLimit: 1
        longhornUI:
          replicas: 1
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
