apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/metrics-server/metrics-server-3.13.0
    helm:
      valuesObject:
        replicas: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: {}
