---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-server-oidc
  namespace: mungchilog-dev
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCwZEljj16dp1lYnmA16VI91fZDXrAvs/L5kXuUGVUldMmMsW2boakWnWv8gPIXPIO7M5kUJ0oGgo/GqUsk0+14V9xa24vPnwXz6bYdu6cIKocWtG0MgyYP45aIZrjgTzi3KEYbrem5fPJeqP9xVxxDWZy57Pc94/JpZRnRz+WN1acGD9qDTlj8obbZQX/ACyhWtsJWBT3ZHVlrtKsi/nZMVFBZAVoB9mohEJVjkxOCCoyWhD7+xUf1uGICFHiHRNjJr2Tj7cF50ubiFGO0Pg8iJs4+IW9bJ8j6873kMePfaQ9pyPcncQcIKt1EI8LR85Giq8t6n2nVcX0rp0M9xvuqrLuvhUF3yv57hHHZES87wBu0PtuAOpx3bSw3H24AU6VAn7zoCqNTOK4ezvjQWUjGe4SzmUNriYPyTt935MGcD173mj4sS46Ialzk2MTVjnbwCVuhRYJV/1K0zNny8s5/ZTxBKYJWIldgHDabLQ/DGsIQcbKSKCL3ELCIc33hfN6u1AU2e+I5E3cdLNHEv7Jw2bl7KL4JeJs8v3oWsMVS8RPr2jUserB5Ec7vSxxlQV+7Kfl52QiQr2HhYVR5MxWlF+fRvIfkovpnx5B4G5nrdcPSJaNjolJ1OMRKl4XUxSgBT1Ipf1Q+m8g2yHz6Xi8JINzysO214lsQoBNY4WFvco8ufKWlQxYVyWhYiIvfKBJjyXsCeWRcA3cUm87hE9XniJCaKs5ymiR5GDKl7riABUnH08sY0+d4+Idetmds5xbwWB7/8NHYeTVlTjrOJiNX
  template:
    metadata:
      name: mungchilog-server-oidc
      namespace: mungchilog-dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-server-key
  namespace: mungchilog-dev
spec:
  encryptedData:
    GOOGLE_MAPS_SERVER_API_KEY: AgAJokloDbH8WgVGRoiW2qg0+WDq03sbbXUajk1YnpfHszLP4z4f3miZ/b7dYhFpUrd2cbdNYBJ2J4hTbdHo161FivsyYm45kg3jtmxF1qOF/KRDB/+uci0npgLZovlUKwX58y962XLh5To0OWPRGHpuwKkxKP06cSWDTNqaQGzOKohae2kxH182MS1tcC6hm8c4XsCSQhP+AoV/uJjMxcRHtnY68zD0NKogW1B1s+GQ6DiVerSXdhRUzcu/SHdNltItcd2zbU2O67UfF11BttlXJWYlLCjRm3FiHwRHjRHZsTIWUzuSL2kewhFjgIchYB4V+v5Ti8luvQLHqg66S8unhZrk6wFhwxZ+Tqs7uz6376FaDo7xBCfvI3csCk3LvT24hF/9LDT3YIMscH2kflezF6ixQIaq5f3ABd4SqaV0kQHEcg2mlvNG+1HoQluIYf3xN1GS0BktGrzW/WZtEZ/PS86VPsAxlvweDSbn0BxLcTPERowLzc+60qNN7AIMYcnuxz7xBL6upBXoSr68atG11GdXX9GS+G8YXAPVuktc89VkM8DqQ7Z9TuDmJDiAfYldMM25vq8qxeqycDjasORFcaWPH1qr7+InCeDRGkAoKPTkJ9zkGLyDVUMsZfULS8kmmdGNRGJIEFC+6Cl3emfXDPXV7iMwybdhv+rmvS9A2vSCSTAzmqgdvaTwF8PzwFGUL6R4+JdFOl8mJ1XEsLZCxj3FLqF8uAAf6gjG6YbIPak6kmuJqk4=
  template:
    metadata:
      name: mungchilog-server-key
      namespace: mungchilog-dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-initial-admin
  namespace: mungchilog-dev
spec:
  encryptedData:
    INITIAL_ADMIN_EMAIL: AgARfhF0XE8dRqNcwIiZpGO3R7ZnqED7ifWe044z0n1NZ9TPnK3lqX72slOOuxNzjhXNSK/RgwrV5eMBJ158E2KQfDq3fPfDO9iXYDZPmjatjs6vDW0sB04wufYqbFpW+4n0RSfn5fv6o07grnoycyzzcESMhG6BgeGRrhfiWDHnfoTPghZx1FNXiU4eYQc2VghN94//42NphB6UX89sifTRyWoQHjdy3fsaAu6f1XW3xbLiprr5rVg6+eOdpMXWzVGcO0AGAjqQK0uSvRlILTCH4cAVh/xHvmoXPxKPNkvabgWSRU9ile3f0uZlxC0slV9QofkCNJUmHj+vPDtKvsvPXuJQLwVDT7DYbuQKEbiaJqynp9JcDayaKbZVahq9xTNZnGDlL/atfk4pkpLGqOpVpJM66OxZvG116hn8VtnZ1DfEss7kWES8bQSe0p3nvuW3V1aTU6IpQXnPuGefw5V+w41lR7f1QsO6vR/aPNH6gjJ+P5TkkJJCwvlnrD6Sbyt0SLCcs9TtVM2l+KD7Wpo8khe42RQZgXBkyQfpw/yTL8t1q+0GfXd87Y09kfvxGhWSvU4HXKtqR+tfXFdTA+MS+Fi4jwc5SRFpJSchxRlxUr+mF3yy3nbrzez3IgZT6mT7USHP/acRu1Uqs8eTRQodXh56lAYcCTy14TMPJSlbcSSAfg+/IYdz6+fsYUZ9M/cw9aexIN4Ht1yGM+wYzKSF85s=
  template:
    metadata:
      name: mungchilog-initial-admin
      namespace: mungchilog-dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-server-oidc
  namespace: mungchilog-stg
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAkk5T3GdzySXGMByL7KJqGivMqB9sE4cn2GDylj3dKHn601DspTJn8kQYrrcTALsM3mHaBkH/4xlLEqYlt3ks/m3UlBq9Ns6eGyMfqZwyg1C84s74hW1Wq9Zu1BcBmFdg8x+gnJqgvIf6m615AVCWW8ovqziJFW2Dyo1vaJf83+Vfx7ytfNwvCUi5Z9NssXOZzHZcWx6XulCaK2W6v2YEq5h2sPUneNIjItY2cXS2IBSmXsx+G7TealvpYXBfDvH90B4fun+58nIC+oSuTBR+KHn0XETAhN//5dxONIujIao/XGd5xA0/eEJXzHu+Cs426OTWdeQHCg83KEMhjf/DyFMsM5K5oDahb5KzauxArYU3TAXRxGgBlDqYQ1PNycqnPvs1gamgsRk3JZYiZYBpEDyo0av+005kzSu46p5pI/81WcpohAIuYQAAp1eX2CrSamD8i1M/8jDmEKyNvImdo9c7MC5A+mnmkpjNaQPRm/On5K5zmzkJAuOku6XarGCWCFEhsDmQUJ+Og8PJeUGl0vedKjhPge7nC2oh7EJowP3wNXgoh8Wl3inwfqY2QrnAlL6usT6UXgM8ZfC/7o4sqZwJwrfl2RvVUFCKKWBQfcrFT6q5McaKzC1nt/mQBnhhpqqWZpCLAAswttLk7i14NkNS5R9K96eP8V9FFmJPJX5R6UpRB8rCqvRiku1hen3mZOP+IAIXHhOBo2gkaggcio5G8Q6NJwPJuwnG59Xj1itwbCGj9myJX0g3UH5iiI5z+5iU5u27AtgzoO5x02v7n
  template:
    metadata:
      name: mungchilog-server-oidc
      namespace: mungchilog-stg
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-server-key
  namespace: mungchilog-stg
spec:
  encryptedData:
    GOOGLE_MAPS_SERVER_API_KEY: AgApO/18bXlrOVYXMc7SzBBU8Lg5TdhoDXea4i5A4wiXDAfcwvaep4TIWBLq8L1l6Ce8gacabI5MPgkZJ5XT9H2ojya7IvYGDzWLe4qduYNoN0VeBd6LD4UQLx1/Btv+w3U1ANyLalwcx/bwhHOFSfVtYPEPrXvIB5LwuHNKBcrpLV7TeBh0RfYAY3XIA76QpRvHJGbm2UhYso7csmvY9Es0PMvbMLDWq/Py4u4rHYUwm3CasVBA5w5vJHrFP/xcVhR89ohcNZG2v3uhqUoQq6fFZS3zwhlTLEyMOPIAcB2CcKxjFdpmk83EaldE68X720KvnqKrRtNIZmvliR7xrmbgEc5zXhJzPKUDyOJh9yAcVKcV/SP8icQkwya/4rmABVWbacm0NmEdw2zFIj/0Ql8LtRKu/UePS8OS1ivj3EK5QMILQCS4KjpD3pIEyrTDLjYpFf96P4sa/iHr4IBIb3SnYgDcV85QyGITHpMQQ6SZxWyYuiN3E3lXGF4VOc8+q6UGPSzzNbPfwdR+iuRwvTchTGzgTvCTAKMafoK3FAD6IxGZHHkphPTrBvPb7LDtNF58HhlVRCaLfAai5xEEJnvkymbC4CUsf8wfXQ8W3M+TSz+NgjmDPpsNu6U3lalKi/v+mPbLREM3ffwzaMk1b/0fwUWPENbbfAoZplhp5Yd+6m84tbt3baiyBUIpqRBom4ZlF2GxqImTZnh5dCJgPQzeeElq8KAiEKHneaQxu23OB0sN9icpLA4=
  template:
    metadata:
      name: mungchilog-server-key
      namespace: mungchilog-stg
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-initial-admin
  namespace: mungchilog-stg
spec:
  encryptedData:
    INITIAL_ADMIN_EMAIL: AgCwoQItg2hyDxuWTCqDZBZyx+6C2qgoXFvFaVX0rqy+YWY3pRIl0wWMwFQBLs/XuOiMW6gM2uBiPwsqQZo6RGanYQBHi3mapnPd4dVzJIELsabNsxHEDD/aeCZp55Uhjv6KDS2ZGMGt6fJ0YUxCuubEqm3RQiCZkvhsu2xSm1//DuHILTVe4uueyn9Es0lsEwMPa59m40gMWcx+Z59JAWdwSAo0a+YLJLOmOoU8R5S/OafdWR1FtaGJGMBWb5TfSsKm11bXbY8nWu3Jby/9BKoSjPntM/rMckaAHA7qEJKTrXjapsYvGG6rRuacIahRlKIak1sDJUaAkptdMKdhgat8LtBtTkyEyNItgzN/4JQFI7/gplzMW4H9oL44iCDhuMG7e93EdAQta3jrkyGUTmKWIplT/yjy832a7+eY6+2MNfnCGHufVu55UjGjz4WszvdP5Z7/penPTqy5hccSziN8R3aPO+Xv67/f1u740Wn8vLUrf4+v12VLrUsJYnBFd5YFoaVZ8JYoVpp/J/xJpCGlW5/r05iuIJPktKdekOlauBwZ5NpyhTkzkIy0y9iNZHHL6YxAH5YeyYvtnKrgZwBdeWNrpXXuqMrXyu7CjzQw9S62+fkGfLE0kYU8ta601blt2MhqS7mJqkL+qrnyL+emA17MufNmX4dDVfKsneITCinBIV/LkHKUBGqxt4Yhrwa+6OckvgulSqD64PSd1ADu9TU=
  template:
    metadata:
      name: mungchilog-initial-admin
      namespace: mungchilog-stg
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mungchilog-initial-admin
  namespace: mungchilog
spec:
  encryptedData:
    INITIAL_ADMIN_EMAIL: AgDDCy7Ag1bDHSVhmIkVwnxw7oXjdyE5ufdFMQQnqOyyKWrDwFY8ytj+VbsWZC0UAXIOYsFHDf5F/obFDh5xevVhNi2w2EZfGZl3XwXctiDl8P0jGALFONj6VXTwUDeJINcXNUbM6UERRmBJeGOjfLmv9yXB4qCbEntT5vpj7qKTTkP8cuDsY8BoAfGvfssAjWSpxn5bJLXgQfu9xLAoL/fqKdvnXk9fjmWnMEiNx/GJ9wna1fmcaweymFvvfuPSTHvMyIK1Gr64BT5VddRLKWwyfqSczK+C8GtvvmTtTtP3C1+TRXWZDfA1jYwA9bmGvbBwAmsZmp2BjPTIYmEw/bXoEP18DlUboG0kU4djrx+gnEtyv+GP6005EI3BxUBWESJO5Cpj4MlaubqvXIQvLnd570DesopiMq/0kjUIKMsHeEfXWqacEFmIMI1QVPUtIaAFisRieB6Vfb0VJ0j3dST8hgoyyKHtmk9ox2YbOnwume3FalH3CixGDRDR2+YLCIeOV350WDTfo1ACHgZqWzX/sCdnRgU8N7W2soZfA4qeSB8yNzTDdtHOlW7l5N1t5QDYE5QDIliAATNz/oY3mDUay5nX/fcNsTFtPgQiAVNu9qr9Ktg+I4GQ5HUbLc2kS9jogoAbJrXD85JuCiK2unEp/Eevd6N8OCMVHHfjz9d6sBq0e7927gIB04HkrDeZs3RbtZF/wFtnlt2ryWHRcIaQqL8=
  template:
    metadata:
      name: mungchilog-initial-admin
      namespace: mungchilog
