apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner-usb
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/nfs-subdir-external-provisioner-4.0.18
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        nfs:
          server: 10.0.4.41
          path: /mnt/usb
          mountOptions:
          volumeName: nfs-subdir-external-provisioner-root
          reclaimPolicy: Retain
        storageClass:
          create: true
          name: subdir-usb
          defaultClass: false
          allowVolumeExpansion: true
          reclaimPolicy: Retain
          archiveOnDelete: false
          accessModes: ReadWriteMany
          volumeBindingMode: Immediate
        rbac:
          create: true
        serviceAccount:
          create: true
        # Health checks for auto-recovery
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - test -d /persistentvolumes
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - test -d /persistentvolumes && ls /persistentvolumes
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  destination:
    namespace: nfs-provisioner
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
