apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: develop
    path: helm/open-webui-4.1.0-candidate
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.4.6"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 2
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            partition: 1
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
          host: llm.app.jyje.live
          tls: true
          existingSecret: llm-letsencrypt-tls
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: longhorn
        extraEnvVars:
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
