apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui/open-webui-12.5.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.8"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        enableOpenaiApi: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 3
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: nginx-letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: subdir-usb
        extraEnvVars:
          - name: OPENAI_API_BASE_URLS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.base-urls
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.keys
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: MILVUS_DB
            value: owui
          - name: MILVUS_TOKEN
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.token
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
          - name: CORS_ALLOW_ORIGIN
            value: https://llm.app.jyje.online
          - name: USER_AGENT
            value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: owui.secret-key
          - name: WEBUI_SESSION_COOKIE_SECURE
            value: "true"
          - name: WEBUI_SESSION_COOKIE_SAME_SITE
            value: "lax"
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              encryptedData:
                milvus.token: AgC7ZDFi2rVU5S/V82GquOGkl+HAG4ZhOsGBbbqk6UpGMH2+WA8YuROQW8ENGK0wzxLLJP0VX/XLeC0b2+SIDZcU6wVk8jgU0siHq1FTUms8zWuUQAolr379BDedh+ImjP/xGHD+iQAE3/GUo1NUnJ5XC+C9VipOMYhY+sxtZi+FnPdMJ8OS9OI3xsKm8E3x1v7NBAYJ16YDzYck61gMT1DSjWBo8oFrUfuRwlj37Tgzn/p2W01nkxJZn4sqGyzfuS8s60tQKIG+1fD0zqio+xxyUmMp3Yt0cJpxNbP6UoaMTxTRoqInwiju9aXepW3oL5nq8kx2+eKSuTr8jbUkHJgFG900EhfZogJChk+bChg0TzdwMzseM+7p0GVESyRE/wzJ8dw9uZUoxsyhvfW6xJ5JZ83mzjV9x5kfxHyG8k6DIBp0xw2CcpOvBW1gqD+gsbw0KfNKcjp+7dzDoSRhhGBMXGuBQJezTt3C+nW9Bpxkv9e+PFjC0ZvUdsD8QnvrcPKj94ChqRfAsd00OFl5L+4o5FvfSMYePs9HHdToCQWfcEcagoOOrxIgOf7MdQOa/h97komIBnA8cFBTV5sa4I7h+ZiySlq6N1iY2oH+p39C7cyZTb0L1k5aP6Sox8mLIIMBxqSyxdEdBeGYBSWLzja/PxZ7Xl+AyaurDkUlvjjc4NaXT1MouNQnJFOAJ70lZaEJrBqY0iNJvmb382L0Aqhw/ys=
                milvus.uri: AgCw+hOr/p7HBu4phjorMq5d0uYerk+Spgsqpl5SpNU9Go7whBXChRvfPDD+hLc1/2W1MybtRRACU3iTFQUDRwE2KOtjEMWjVchwZRzey0uca7Dxv5G0BJDRtxabAlhSgu8H7MTzyDDMKjmlWhRQxMSUhG7G8+inqaLVOtA1bPAZILcGZHbQPo/myguo8S768TbEjROq4+U8EdtVIuggAcsoXaupruHFXdrMCZDHoAYsFUMBOeYngKc2MG3ER8SejLt4v7o+oyVM0b5nt0kb45I85dnyrhMdIMLjaRWXjpHfiP7Nm9ZHEDWMYJy4aLUIy2PgjsgCR/Ao9GoJopPMXHIGTmxizpFqHJ7CKUKgCIo+VsJPkgvEUmvD2db5Z+qDy/49nhHF7ZWVMLPCjKz+l4Oxt3Jg2Z5U7HjiP268CQ9zYHClzNwhWMErKVMsm4di8wjnVtqu3QN5oY56LQr78ZUpdWbwNvnzSST2v5SAfsplHGRIi1RvAvQSea8ESZ6LWz9aZqs0PYAD6RrsweZlYfYkHFvUesMM3MDiqv7jMbcWStlgau/8n1nzP1sUhXw/AhNIXzMhcUH9iQFgVyDWJzWWM5R5k+fbqhm+tiumhy3pcIc8SdG91gjKuYPjDNufQu/ftgZv1Dcs1eh3zvzOPsANHOWnrwLajWkyLUDew02RC/MOQ9c5KdL9APa5yVKkE1HjupXK7Q8KjA70kFdZbZL6JC3faEGIbGzTq2l7vWVtVT41G3ZalkjR8h/tSqdIQTe5IT0=
                openai.api.base-urls: AgA0mXZ7B9zJT4Rk/DeE/Ra/wcbDvBlKv8Yv/L6wLE9q2bOJ8bqxtet16a7CSOXpQoKSARHFXrMx0eYLtguwNG4gzVIRHh6Cm4nOuzX9KLi77SkKdWxlGmCkb5oNW6FNn+M7gnvjbbVKFXDRCG3iflglUntWlGdXwJh9t7D22Oxo+DqVUsEYxPY/tJ/3yJgerj7wLVBhlseCG8Ekqv46yGmCGC88ahowtqXFmTt52M91oAEpv/ZeCxpTrLyxEsgWW+roLjf7jtVggiriXbBmJwW6dxwupwEJWcdDcea/s886l6S3xXZmnVLW4NSZBwg6bK9lkwY6JE98aj6VBmgfG8MRJWuCH9zl8J1CEiKDcjxJDWMyemA5BZswOer/JERMyTPrlzTiJd41r1ye6KNyVOzU7w2U7xJVpMq+uUVsqaPdL+lsMDhuFFklRf7/TlbADx84KB2ZjetNSiT6kgqRQS/IQQVakhkBi6BXVwYFaHdwMRdS57VUQMQYlSFPi/FpItW8/ZMvVu9XcDp4z4Mzz4rMJeXaelc+mIKj0TETirqWobY2BfYdZwF7QupWtKdl3pQHyJzJzDQpjrNh5Kuy3RSqm86CXBJHIxxluAH6n6uLl9wD70r2HOkwhC5YX5UfjXXufGGZYdiJpIsMnazyuOrZuh12iU4nNu+YukWB1RvUzrOH4CQeWnMjahIDOqUFYAtQabUkvGoy4yn9AXMH9GRmt1jTMFryqX8FauXh2iLEJaDli1oEUFJiDZ5qCq/mxw6eXkgUZbwShSt7dbqy
                openai.api.keys: AgCEl4OS0Qw/BmqVdslNjqJU2x5KPRF0kkBFDSfrA9qrlzBjz1Yg7q8a82T1TRB05sO/dswixdzAdTEiMnHrk4SfViXE+8yH8L6ydy1B0E4jVKICzbviVU0Pn+iPBrXLC+3Mi855jfyVXRO/0CZni00b7s1yKC8upHBurp4MjTMaRcBxokEcy2acE3FJUWmm+R0G6VrdoFhrbdNO9dgXxxl/+kWL1xCzKy4UmLj8l0INsNlYG4Q2Gd27FFajn5/j/tnDM6hFFPCDy7RvfvuIAKFiVPyisbfdm7eMw+HZDnsxRVCAljUcahs92LlHVREm6eXZd8hHM0F7X8UYHh1vjxVXp3KdSh/shMbx66Zbi8HE9UKpqGLDlXw/J3DxBXsYloleDfiD7LIwzDNXu2xyRLlaYSJ8RMQtRmI4vy1ETbzw1IUPfQYtho6VtJwYeAilbDkw+GGqmuq6I/5GRz0CB3IkngJASBhsvLkEsRiB0ZvtHaoM9oMtVI91CiKLOkcaIyvZD0i6Pm4QHGrpQjBUGa1QcnLdCXT3WbRzt1Inv3Mjd9bpjju0iXTq/hg3JlSyHeTchsbAwLiONU+fB6/8NEuIy7nMB3PXVZQKDaG+WfndWhpeVZlpI3HzeYBGxLOUMDpurlgkyGMC/mNASVwTW/Dtwas/iDEVihf5HxlX7/ophj2oVXcU6H3WlQj3hc2zs0/EzCkU3PeI6uRCVHbSQf8/h6/m4jvlwQ8tW+Y5sO46UP85BPK5E53GPWrZQYogblaPpFyE8lJlz5vplvFM8GPbyW5+AodtruYflMR5kqEiFZgz4ZxDeSzVdESQ10YghBl6sQBpF8iBtwLyETEVeIAtswAMhbzeU2OBk/Twe55Mczr41clwwGUPFT/BpybE2fFjPlIUapggVXkHd/zVxAH0uEUCUkOwd6NYv2UEGAcm5R9R+y43t5FjWggsUwKVHukfJYSxjQZLPZQdZRGxXt3IiaS5EhR2X9+OlNVKIUYUNAjDu1P6frripAhf
                owui.secret-key: AgCyenQbLqYj4NQUM4Zy7ZPM2v6P2sFFJ+j5+j7gZHF4rU58fRZU29H26EePsXzPgg+h2FsSNY7DStUvgExpSEDasWDGIQSJa+IJDUhi9mbn3jhu/coew9SY2kNM8m3Qfy2Uk/ZsOcmBPxd+9GBlpuqJ/3uRVcP5lSQEa7WsfrMuC8kJWS0wdCtKfysHlxZ+gc+vrI0ho7O73zca14UyPJAdfQuK9L4/PiOJUBZe0UYMAo4/uyOF/0appL8Gz/X5pD0kB9kqAfwkWbjyteeRohaEqPxeJBYwq4B8l9PTgdzeWHQdbdYAlh5x94hwlprWj/OrhjJOXZOGQKkZWe03JHO0lay+x0C2U900EEX7d5Yj/9maCZcHtAzz8cefMzWPkmTH44vSXexW9plB5Q65FPLC+sbx86JADt2wYmBWtPld2R/O6YYTK0dfZ8XJqwSZUovCfxLTbQiAyn2DbXmS2J3vmkCy5XQuk8P2utxXZAjdlyc0+04UstpX8X0vawYYM17lpTQGRRyO3WUPpyaTSlKZOHQvoeBlLPxBH6tV8HTIX3x47639MJvK+Yu/sK0WjjFfcRbaXeS/KTVnG4OocQDpO091CccCY/z5eeEgFCNpUCAYtH5y1J7gUUklDS8+rLz8jMcc/gohTJtMwq/IC6U4qwDa6aRnNog9KJcMS2JSEI9jb7rCCzWR1QAtiCBkyFISctNgyi5wzrAPqK4Sh+1oClvbhIg3dxThJl9jMXxCFqv7
              template:
                metadata:
                  name: openwebui-creds
                type: Opaque
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}