apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui-8.10.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.7"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        enableOpenaiApi: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 3
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: subdir-usb
        extraEnvVars:
          - name: OPENAI_API_BASE_URLS
            value: https://api.openai.com/v1;https://guest-api.sktax.chat/v1
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.key
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: MILVUS_DB
            value: owui
          - name: MILVUS_TOKEN
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.token
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
          - name: CORS_ALLOW_ORIGIN
            value: https://llm.app.jyje.online
          - name: USER_AGENT
            value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          - name: REDIS_URL
            value: redis://open-webui-redis:6379/0
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: owui.secret-key
          - name: WEBUI_SESSION_COOKIE_SECURE
            value: "true"
          - name: WEBUI_SESSION_COOKIE_SAME_SITE
            value: "lax"
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              encryptedData:
                milvus.token: AgA0w/rTS9BI22QfdvV2erDK9I6dklDwSql1Yns0fmokTqjp4oSD2+2gyrTKTRnQIwKeNqv+Z16WZOjIsgTX4AWes6nDdNiWR1w0nVbUstI9O2Iybzi4QNa4gh4E1jSRG1o2zwhFOlaGqhGmQCrxyM5SQXGwpDzhVCJ1v3Xk0UyxN7nTq3yY0GcSdqvQj2PAnxPd5g+03X648hjItl3eNR6NjCzN5mmxzid5ZiGhQuJzeJZvI4Hx35orwTKgN8N+wiHrtkxT/yPxH8DvyngP52mPwD23HnGh29lZl4EfkEtsV3ZN5JAlnS7xXF/uz5VB5wYSvHIpiL5f3j9dFjF+cqk061UOOR0vyNW9aLg9PvCvCShh++BGwrD4PpmwUabKQWU95UAo9/iQ8ofAKUuhxTzZdLs/0cG1dPWz5u0LbZW3tvrF6nsDS0AjTFmSxX6dGakzGqnA9uGGomnzQI6F/b0b4irxnPrX+FI3QDAxWd3b8qLaG1UE/+fbgqOfpSvJbuXr9aMxgBTbYXZouYsw+2AtA7sdvDIciMg5e8QoSSd5vUuFzS9zejNSjCfael/ewfnvVQmFltTNJNVtfgSGb1KZ3T1gCRSStuzib28PiED8JkfYBIeVc8Yg39uiP02VbLWHObwCa+H614ics1HiDylw9yRchy6bLc+i2a6LYAnS/NQgihK07iMYC4lIIGD659gPb0BG9FssWtExAI0Iqcrb+54=
                milvus.uri: AgBj2pxm2OzZ7IRMXOiLZSoxSduHunLbyIYDXqx7ElxEVXL70VrnrFwVC3EZQeoVBxul+QVKhUxPDUx1m55muRpgLoaYBLxyvvPDCm5tQtUXTpEnX1huanUiXszeAwUE+4MDpa4FU0KlyhHijBnjwZDXLs8QHaldcr9eTQ3m6+4YKXJ4YBQC4zrJwM/z22hJHRTQxNw4VKg23V6lBypjPdW1gN4jEtO9kBGPp6+6677C7gg5DnEH1SwYF3HjFpcH/q0cdJwXmJGYynX5g9Rcu752+UVZbeOspJxyOEfLhiU1EKUafLbkA6JVnjbrso5pOxUCQyZ9O9QqFNEzr7rxBIZkwMv89829UjxPx9+UUEnqqi+qVMJfjcsxVtGTRNS4GxU9PakU1edTHC4TO6CDkQVZSz5HAZqKCLWwnuJNPAopMckGJHenzrh/B3/c3ei0LB55j0A1vi9x6iwupK7J0UDXdelwfNnHQndPYqKBWmoVxPN5YzdnrFGp2iqGnfRUD90aAt+Z4TvhZE3Y6UFwLMzZkEEjBCXwC7CyZXQWoo24hgPH4o72vyFaDvBWI9HfIZ1BD9MmRAx15tGjFzSpa4fBfkghtiPsB1OP4YQgHlBr8M9fiJ0mvZ+ctGlDP05y4jxqJWXrkAhd4SJQUFnclK01QBb7zEV1VYPNGfrge6rr/QfL8f+F+H6f68yfMyTyMIc8Marzw4EEIv0dFAioP6hyi7UXf3CRJQ3u1dWUp998cZ4tQeMv9CVtGjx6S9Tlbx5bQEI=
                openai.api.key: AgBqwKwkQgJ3Y+YDsGOzysRxZBlQbYsBC4ZmnJLK7FtG9ZL7IJlwsK425/1T/ZWwe4NQfxbkkH0BNDruIJ4q3pbAhojE1gZLq2/Yxm/0PIuElBj2IQUwrPfNeQLxfmcVJuY57LL8nAbtZMRwBqSLtBNa02gKErWOGELXqm0nEYycmhKUAvSFbR0ImsekSqokXZu54/pRhIuT3G3yhxGABizZ/RaERrq6XKdSU1zIMiaD0hKL7djP67r8TNSdbuGl6iVihhAxb8GcbFYel1ZKZzh6T8PLRRq/X2uVTEAGPDlj1oiDi+nbay8Mm7+UboPhBViMmJOsmTTGXw80OB8J/ARCEflnQOFTlMhH5U4zwUbNfoN02+pafOTzEjH1M8/Jg7DJSfncfpnZYy4sZJBgnAn9ODaqBKfGJ3e8S5WW0+RD1rqgGZwTB4ZvcLHx4gNSuwW75Co8RDkzuTwlZ/wNlCSUew19pKqEKSH/uc2oduzbtodmCnHJBBSASHpqVHzu6rnoTTy8wGM7cTAy7D9dp57BReU0fenVB9fMUPYFd8LS9Ne8G9bHb0Y7NWUujrN/vi23DbS79aVUCTw73o2kSq0/vitPTpgRGO1FHd2in5yygDLnwh4e0yY8VinSzEapj5tVf/nSj8AzC9y2mmnicw6mLCPSpCPgmyoUpVbB4chDvWZyuXp14+RB05UwojyyJUD2cCHDpoUNY4mZ6dFaQUltsa27yhwiVv9VI9+FRELU3EVeSudfk2xP86XgU0aVCRyncQ7UFG70/f4OYKcME/21vmWBC7rQg37RuZih/FjrDbgjoZ9DDYHvpCsHw+zQeues9+lhIHlW3jAni7ka1Ms1LGgTiRqlTURQtN73O7LAr9/eJYy7LJxOZpHO3S8NjRAIS98ooEm3UWcSrxtz8yH08n0R6BK52rnmbBBxJfG1NyEXRkiSg3UucFCJBb+N0kG6OlgZSw==
                owui.secret-key: AgCyM4gX2SJ8IOeSS8ZxxknVCnxlHvRwkwvFSA+4XeqQL5SPO/bna9f1aRCv4oVeTcwDM4pbpnR/m+RlaxXzYx879QG+V7acdDIS7iiQ+57IyTeVuFAZhH3FCH4k7jWA2+vBknhXDc4YYTm/v7jXgbAHKtZp6RdJS6U+Bi0CzWJHcWbPCRjFbdjC9mKPBmSBVsv0bTWl6ZvSF2AX1XvFrDkDRrsBJfr2mQzR9wNnAkqxPz8QeTt6kJz2mYnho3Yi6zGjO8l2A+zcg2fA9gDjk6KZtyN4YKLmxxIwLJ33jIfQNJ+h8GiR99V7FGqdhC7YWuHCmUlrDmLE0VQsQlMqn9+Ize6VUbs3iPKTkUtLpBEQfzkQFamyJIvCYT6gtaoee8o6D+odizDR8oX+PNMFKpeanbmauP6s6hMxdIAHJJ+yVwlM/9as0khDKbp0IOZxleXvZFEG2xcYJFwNr5IoT8aVN7RkSNILXWtr83CijEjRFP6yWVz3Fnzal7dfYzqQOed/sfFwze2OanvCrEcbRb+wUYTdN4wxZGjd02sSNA9wxHm3aoQQ9/a8CejS6k1lgVgX6ydq9BrNwF2IvQuF4VwLT405f6BHytyeDERXh2ZoC5NwlERbVK4YPSRXXwz+QXbTZutuDfB5rSEWdU1OaWAX5+kaPUm9OGs9WzH72hQpcjgpnPhpz9fTGzxkWnSYVcLwOH6fRwP04CZrPd/Usr3xoXTmOaWqd7zFH0PqajJwG/vq
              template:
                metadata:
                  name: openwebui-creds
                type: Opaque
        websocket:
          enabled: true
          url: redis://open-webui-redis:6379/0
        #   redis:
        #     enabled: false
        # redis-cluster:
        #   enabled: true
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
