apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui/open-webui-12.5.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.8"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        enableOpenaiApi: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 3
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: nginx-letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: subdir-usb
        extraEnvVars:
          - name: OPENAI_API_BASE_URLS
            value: https://api.openai.com/v1
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.key
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: MILVUS_DB
            value: owui
          - name: MILVUS_TOKEN
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.token
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
          - name: CORS_ALLOW_ORIGIN
            value: https://llm.app.jyje.online
          - name: USER_AGENT
            value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: owui.secret-key
          - name: WEBUI_SESSION_COOKIE_SECURE
            value: "true"
          - name: WEBUI_SESSION_COOKIE_SAME_SITE
            value: "lax"
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              encryptedData:
                milvus.token: AgCTC4AxiuHacJlHxUFdsK2KnKj+wyBUExvZRioUdK/eGH334jfiOvsRTyFA/QbaWkrsak7Wz0Ok/BIIdTW4/OA3W0134bd208aMqY6KLXlcZd3uUcq9cmwyAmQRmohHwmZtIjq6ax0eyWTpT+n1+IsWoGOoGMWuRrJ9QfQDtt4ta7PlG/6Uhn2bg39DI3BSbrzbkCE/CjrCt0y3W3cPZtHdw8ihzKtivTtkPPqnl+CaN2vfwkihZsfxYwOh4FeqCu7aOTr+wIAV8LEE+iryU1GuDEz0W4Fiz1gh+UU1kIQgV01fNXR+waJ0jxlezTixhcOzgr3qelBRqW59IhWJhTW6eMVtvC9pkyTTkURrwZw++QBWXrJJcx9yJsjFkjzVsdCTpk/CGOng1zpFbkvZjKe1T5zSJxfmlhglQpzV9IAcscZtx2dgToSPWcnBmHILdFpfLoMFCxi8HdhMrQFM4DNKz2t3Mw2hZOm1KK2MYcXK25y1WddihD5bUP6ETw7H0JTEf9FIaW6e8HbXrpxdcBQ7J2mvYGqWG04b29xSE0bYNathH5nXRFCdkMJPDVpiG9gh3h5BSOl5K7MbGK6SwZPCB8HlA7iQyp/OUKEh7+1swfJdEgnBmg1mNp+k3iMg1jHu8HLRv+Z4p2dCNhVeJr7Lh71I7njBlKRyVnzZ0+LcBbFqjkjPW1paKcCNkc0grvjF5WLzgBAcH3DFhqkH94O10uo=
                milvus.uri: AgBnbs2jOMynf/vVdYuD6ZYz/uD1S0VdsLWp3lSevqZJ6HrROyw0CqvEL/fQuSM8mLb6vqhGi5KxWKGToCKADwBWOMkwsmf10Gvw04KXVs0pWxxP9fQ9Fv5yO+9JxHo5ON9DSKkRE/ghWP6e5qQvRwh4q2hZnz6NnkUW39R4sosHHUUIqPfs+ZhZO5foI98JAmMO90YK3nwN1NR3PlxJu+a57xwPVAMr9S72WLCuP44xOBkUVMotFmlzipxN6cZ3Wou2vutHBL6JE9BYEHwFXm1eJ8tmwqV50DS9g6oRXkjvlI6tCbuwm4KPOu79TdZr2UiT3qtS86kMrPq0RlFI02Tl2/Xh6NeYyc3sXFivH/TbdFrtydQOnHYBpH8k3GXQqSaZbc7aGxfAc0QtzQkPe7Zml0bCF1IquZLx4iRm8GTtF4HJfl+sO8E7D4drKt7DMBFh35umtHccZpEB04zRK32zIDCQ82nwW7vsOWWZG7cCQcOU3Pf37Pcx7+QTvEi1LnIL6ABhkXnkZKL7Rj8VxPNkRmtegwdXHh6i/gwduj7kUdYAE63EODYJGuPstMz+rVdDXNcbEKRflecIrjXzzlRgzYjMpJO2vvNvdRrT9TrL9l1M9RTOvNstvoylZ2QEJumasKF3x3PjN/OMf+a5IIyH/ingbcIdYJNtpe3fZHqUkz3WW37458Of7w7BUquPmlfdGKLnO/bZgUKcs986QS/67XzB15k5AUTI5wsXMltOMVz9NHROgkABZJzaa2AOierOO94=
                openai.api.key: AgAjY0MXD9Tq3gUDwgaytJ4vLle/lFoCOb0OnbjMtcxzk3Lu91zuHHa5AGHA3t6G7NTGrWclAyAvojjWiaYFwQhHpGsgQpWf/p21p/2PhO+Fj7qamvBtjqism6h126RNtyE/l4B5EjG8QKj6j/HtA9gYuC5w6QalyLHnATdvfsLsqjWCXaIyhhg4IwWfFmFrW7ZgbuTzZ3DkIlyGipyY0kq97nY577PKPxVPi4e7ZpVWcIUQayF+VXDuYRdg4WO1qi6b6iNnpUyclzbMXK05DwsoBjNnmDYHaHoOQ8cr+M9KJR0HhMu7JWmh5fHLmtb/Tg0aRxrycP9wbpNDFsfZw+gPQDE0S+FR64pZErs3UYym5d70/zRimu6g62so4IhYRkXo1G/y+6GIKpqPhRV9IPKlxWa+ycUljpxgrIsClZW6GOsnYhd2J7/OBThHSU3tCxY3e8NJljix6OBlRRhpeOTKVfqgq20QlvOCQWHxGQGfunKONxTXmpseVD19WjBMAtg5a+O5HOx19SWWtOZSaPq8f2qyXPhPMcB8wWwLV0Ci1WfmcXSfNEPpfO5ZOKSGHeaEKoq1TP7iKwom/kRxhloZlqz4aic1/KvcQcm/G3rmx3hpL0wDjRIs+f2P4pyOIN8nQmJFd9RK7inwGLhQjvr7ic/pZS5P3LIBkgz/jAWco112nwzsnR+qkH7EoV9QmvpjxTEvPzrsCcnVgfyX95YHO4ffwmA7ABkrudT+oTKwZYstXr5wS5qiGXgJBM0g/LBukeU1f6yG8xAIWTAGYCz899NerG6mLIKGvLse0nspnfHkFrgENolumQ0Y2EeY4DyiAcyKAsssSqG07P4d/zs34GWgeRpHP0dW98ZdvOq5ItYyALmnxOCSZFs9vruRxr97z++y/i2bwI5gaG66I47vBAf1qA==
                owui.secret-key: AgCpmZhD9InPmW4bPYqiNFvjaQsowHIwoqgl5dwsSpBfW8rzv4JopoB5oh6CbOSdVstdRT1dzuKGa1ymdNgLAnZOk/1sHOo2NtReXnOMFKZFacdWExNAOuRE6OBtaoqvfzgO5TWXp2YfFhy3Wf9FSrV8CYYz8dlAiUUwb3PgwSLLqGHlZkR0UaKXvxx9kxQol5GmHruQmQ7+84qL0D8H0Umm/PrvFL8tKNUzN5U/BhkF6xPnsSr1uPZpyffhazaJNJvGJOUHTd0pi8QbmpCrtH54flPD+12WvwT7qrQk6ujXv8ckf4os36+rcur9lpW7vtTBsiv6q3Ywb1CUmgdUMasEkWhR1WYmFvQC69OUEKssGGURfgEzEzbFc2M2WXleX81aWh1anmKBy/gY93inR2hWwsjQ3ySOGzxLfTLwgIopejENsuAFsShd23hf86Q6vEz9nveXKkKZMvFahOpfiwHqxpKYWYZS7wI00TOE4qM1F6nxPZx8YyiGdNL9pdurwGCW+G1SbJO6eAyc8sm8fKjp0h/qLAYHAfVhD5Vkfqw7idfflXgCR8xzidMqkt/X4rODLlUWYjt1arzaeNRVqW/vXfVULQdkPgBEhftEt1QmY/solO0zU8IBFjk+0qQ9CXHGHfGPhKur4zFmPRcksojbSo2XNe332Lo50Hp1+4JqlarU8kc67P2wRKCi+bBhswuiPA0fm4Hbgmn4INyLIH9uXObKg77MBcDpdWeQQWvig317
              template:
                metadata:
                  name: openwebui-creds
                type: Opaque
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}