apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui/open-webui-13.3.1
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.9"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        enableOpenaiApi: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 1
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: nginx-letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
          timeoutSeconds: 5
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: subdir-usb
        extraEnvVars:
          - name: OPENAI_API_BASE_URLS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.base-urls
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.keys
          - name: VECTOR_DB
            value: qdrant
          - name: QDRANT_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: qdrant.url
          - name: QDRANT_API_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: qdrant.apikey
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: nvidia/llama-nemotron-embed-1b-v2
          - name: CORS_ALLOW_ORIGIN
            value: https://llm.app.jyje.online
          - name: USER_AGENT
            value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: owui.secret-key
          - name: SCARF_NO_ANALYTICS
            value: "true"
          - name: DO_NOT_TRACK
            value: "true"
          - name: ANONYMIZED_TELEMETRY
            value: "False"
          - name: WEBUI_SESSION_COOKIE_SECURE
            value: "true"
          - name: WEBUI_SESSION_COOKIE_SAME_SITE
            value: "lax"
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              encryptedData:
                openai.api.base-urls: AgBHASG4sSPEepo5bf/4Tl8nnNHguokHzgt27FHU5Spe6BppaeYSLM2jmoWuHuhs34CXU/u2ZbFQrkzJxNcLqa5fcKpRSix7zpX0yS4beffW9xttDbHUktIZDFX2wWvvno3GIZ23+Gw2Q5K20P6rGjF4JXEqKyzMGESbqCQZ3yX39KcdUMvoIHnmmH+j2lzCXZWg9qgXJg1MzyDwqLrFrZDFWz9W0r9+Kb0Cu3pclfv4yYW6tNc9sdqS0AQr6XveSCNwzNrBNxQsFkAWaJkB2byp5c4GIT7R6YHl14qwGXZ0ZPJoz02yya0NrECXJe3regtxxcsulVA92lFzJ6ih3fCKEE5kMl218SN2n143M0Z0Cchsr/3/s3Gs3+676LObgmbeMHj93+AgEGC64LOdTHbymMTIhX7Vz3eBmOUfTtdWM7dkdi0XQjkSWV4SfcVkP45JWlmxNWSwYqpQ4g4aCRv+RxCnfhwgF2zbXrCdZPTl0rBIcp5AOHk7g92VVx0t1mbF4CRAnIqCCsXGdZ3fI6rrMEb/XikOMjuNZfpjWuKAt8xrW4OKEg2Ch7cXYKCrjqcGB1WKNdFz77ckaNwtP4zYLrLvqnmvnItM9a0hnpwXYLhg+eNv+SPJ+hLFVvYGEAw3KJ8v+zZTkDSAfi2AjPF90NwS1P4UnscK70lf8mxVugD+Art8Hcity9R9NDgSElaFEzHICQUWdKDUUHU2gVI3lv3m3gdX4g==
                openai.api.keys: AgBuUeI1FnBX2gNKYOmuDYjvIYbnl//wSgF0g2icgH2ZSVypdp6C9KPAdrN5Mhy98RX7AxOTGcpZdLXcQceeLCcAv3Emr77V/ziaJXG4+Yj1D8p+TJrdZ290oK11MGyXzIJuldHl4zY/1UgXkFOaEb9piF05pwKhT8Yc2jHIj0JLWK2mJLUPgZLtM0Htc93Brt4EoIwJvxw0Mr6vEXoMJBp1H1Sqw09UYeeW02xHar0z224QDQF3qjQVzC4YZOEvz9WLUrt2w8qAc9/lILAonog1D4kopqfzHHJoXFdbmQNk0a3XhY5Hq/tXdM29PV64GaSN9DY/d6wPaa310aUgCKu8Hu1qhrqptVCa4qkd0BV84ADxMyOLPPIkhZfJi1c/odeazq8d+mXIsDToMnklh42ZQbLiq08JP48dgsQ2KtTwkskOnR+qi1rSYGO/t6PpRbRRFC21IAN4pMvYQx+d7QVVbJwymL/0Uzq6YWy8u9YwkPYDEjgyr55NBp6LTxVKGQiYvBYzBZBPWwURd4Yyd8mkZyWUXbGuNRLlMeIkb38AgzfMtGNo4+rPbX8ALV/57kYjrLYa8nBLa9fgU9knhTeDyDFwdYGMvTfYrzY2fu/VLke8LStBwNba07aR0B7K6pRSdrZI3NbhC6GPpVl8grEP6SsyL+pdCKqu3Sca6urVnMCnmUp3YvRO55uHKagD4vhnhQ5dbQ8Weg==
                owui.secret-key: AgALkOpXJnsI1w57QYbCJVH0gEh8eBZ8QCxkgnq/b5+Tjd3Acf4RejOUeebgFRdIeVKmihC9QKmpfr1E9SiYTKt8IbBsiC666XbUQqD4W4bG5rlbp7zIt3j8/Tq9pUfi/KbSGgJcJV8FxzCNKmIgtnrB2W2NYbruRIB1QH6kx1aPyEcZ6lWljOQWmDw1eupSvMyj91M0j+w6/aK55GZbRhUkNZ3TizOzHrRI4eMWMRGOaC5Dd+J6Tlq/Kz8NJBKqNOplDMIonRuAqHVoTi7otL/3MfwG7D3Oqr2Z4OfOKGJgjB0IbDgaIdmEMQF7KWQYgVQe4Lx+AkrxfPXzQfI4gnySDX6He66X7yMDc55ovD+yx/dpwGFTnF/U0Q2gmLZP95reeW0tt5aN1NIspzRSWxwap9Ebfml7LE9cnjzJYsphpeNxN3MWpZEZ2I5J3HkYki4+sTuJ6eeZHQJOV/a0DVD17xfDHSfr3z9OYkR1HgMdzGu6fUbHsKn1oAdFjuqogvdkgGNj/MU14nsVZMWs8Rc5wpVCYGqlG1Dcnk1QPDy8kJAsC92M18bdCOAdgrAzujdRkCs+3Ze0yEGPJSP+xVJdHBAJlkHXnrY0WnuD/wuGmfFPNHeK1PDNuSmr8XAxsNjuYIggsNvcVwG3c6reOdUlnto+V756tgdcC3NiLcNy0acVT0rmtwO8h7Wrn5hH/s9t2rAljvRPu8c8s5z8MXuaxQYdRk+dwpGnYIrYQAkq02zg
                qdrant.apikey: AgAVH2Y0hLy3Vy2pyVtMj9HBCqrAZjWbPfjMSPUmhtNYAvRw/VdnaI3cBop/SlX60T+b6XdipqtobbLwnV5H1KvS7P8pVAmGwU1WiMcZoxxEGpno0o1hSEpOw6wVHE/42kixyHFgIUmSH9mOR+N8LumLuge78TopaLIYfJVowwcTGj3rV8S/ekpGwCc7EcxH5ohl3A2OsHIcYsEDWLousUdw95x8muDedGWebaw1hIEXhGoCmggLrtxDcZRr+BJO44KiHfDcCUxs5Mfg47gMNkK2YdMqaauKFkmqlLm0umKjTVIBUHHYHvYjhp4Gf6+UgEN6sI2OlPCBn1OxmEaYj/+DHwloWCvA/geKjtYdEH0nhX8kOsIWWvoWlCk/BbKc6qMRSSvLRwhUFXuKAGmsjY7UbhssAh9djOpLJsDzgwUVa7GEyRXR26GjA/TadQjrqkYrrgH++FChO9kFcYwzOP5V222sGHjJ/py0vKajHA4MVWmYRwjA+cmzhhW7soieQKTe/+veWQoj4jYBMovAsw6vIy4eqv3qzZ+S82Xy9D5+dIxUAaaJg46tEXIOvTJfM6Q6wrLjXXI1vO+ubqog5eBYDOr3c8wDM1OPF8+O9zvozFsRRwUfT2Cwr4Dta1BS/rCkUvUEoWj2TKl8NJeNh4IjSpAuJtv6mKefp2sElGGwGRZlMlYD7qbwApHHXMYLTWb3cczgYlayoIsc4ygBsA==
                qdrant.url: AgClc1qHRI5KPNA4iXyZCLU2kILan4NqC7WiYTm+YQxtgW5LpvG7Zvo7tueqhTmWRrpg7mLEo0PHQ8nE/qeTWEQZINSC9izNCLn6LJvY5BIFAUgqIKUXFuKZbrbmFNkyOd6o1MAlGvag6xnix7zrlJLQVNdNzX11tdDN3DPFlfcGZisSrAF4mm8KO0Dh2j1mCBgPG5X0DsDIGld7QbqBd14FOEUQRGIIC26Un+hkNQH640Al3IlApuV8fgo1dfXsCOMfSVbsKmjtGACcGqbJivLp50aaT6UrlIb1Z8u73GJpJgYloJmFZ5XGaDQfmH2BXRDryTPJixcBWZpsH1PACev64giRsneFTdGKa1eoh4JVJh0tLffFC4rBTQClKqy3k0ggkx1OJg7M+j16cNSaA1zCw8AFa6ZfmH7nKl2f0FFNszOL++SxeMl/oq+0cv8fM5F8HIs7Zp6zeVy3d++q/KUntvHbFS43/vxF8H6uOdk0lsqRZyNn0e11OUw5T9HDkULMElUeE7sW3cnLOBnRBhDzrR7yf98Mbu5al9q25UWbHh8N7I8ueW4EIJcKe0bJ3E4tBgMK70xC/kP4PEzxgzP/Dc2cJMKt2W3ozTwaPy2sZQNvZ75XwHHq1TA/5fhvxx46ourFJNuvC572R8Ml8YKNMwypCIK5anZEOYnylAa53EK0IrOnMiH0LvynLvNHEml4ylAkr7O4b7vbzEPqH5NKI7E=
              template:
                metadata:
                  name: openwebui-creds
                type: Opaque
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}