apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui-8.10.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.6"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 3
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: longhorn
        extraEnvVars:
          # - name: OPENAI_API_BASE_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: openwebui-creds
          #       key: openai.api.base
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.key
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: MILVUS_DB
            value: owui
          - name: MILVUS_TOKEN
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.token
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              encryptedData:
                milvus.token: AgB7ihDBwj/8iDvH9miYVsHKArKLfpXSFeoxDQaZT8mH8PmEMcyHDF/V0NNzQDNNPfa8peCwHH9GER+GNznBDpalfmvq/Zp6hbE0SYAKKePNShGLtlxnLJLAcYfGKQc4v7YOS+rWKRsXpCms/7zNm8mEkKWuuXL5yPalF4/u1jl4wgmv2NNLwbz4ynVAoQqdfmWm/AJSpMKnHc3gXJ0RJEn11fRFyx3xKpWMOSaZa0r/EJi192I0TWx5hZNgvcu3BLop/gGD8h0t7cENk+F2WgCH5ICzjdTmolnvYeA5bgcz04dkxtsgNzOMiJQxrRYfOhXZv/8LBt2aGpx1yuxhmSg2uewKkZQSCK3eO3ZPuorlOq7xigVj9zCDc8O2fvC+HeSlVHrPGG4BGJd6LvLBciXsAanKu7pINnsSrQICeQHadfi65Du/6cDBGsPUzXjWA9UL6rKTHZeIWumCaR08RltevZXFEIr+sIHmW/NI5dkORoejn2YZvZx8dbpDmhNppc36AHtHh1K6k1U1oZHrIFtECc/I8qAi0TOMHSCUUDx6hSwvuGiHfv0MtoIu8ru1pSlU0bLzwhYILRFWbe5gwK6pC+/uMXY/QCKUuuFzoURV9JsUaq8zxerx1k5POi7O2/8KqKE4MVK9tqr1ZtAX10rQSPmmmep7ZnQSZZUedZZCRLBnnSUAgGwV3zcBMRj6PoLa5VCVKJvspsGzk+2es4nTaQU=
                milvus.uri: AgCFprF8sNw/oDwitmQsXAHBej8nftVcr8R64+6Ibg1PGImXKncoO5T8x0fhtuoU+royt9HGRsU0VFHLJurK4NjtHE/kkptcL3YHNCNMEePQ6ftDlXkAZJVlhNWCt18Gm5RhAZG4b1cfTSd0mOJKsQCb/XoMUgBT4Gj3xzDljdkgCQwXTXGoVWyPpYAzL83H45By85aPC88qt7ytKciRcmCDLhw9xvP85DD0bvUWG/MxsziNrE7duJbjZVvXy6pqM4icBq5hjMKYYMUtR/tQRA6qNK7mXdY7HMf1lrfIWz/ki/VHlcR6kDIWkx+TgrWw9wcs/RjsfgzgNBtlrnH0SrFcc7m4wFVYsxO5hBYsEyx47+p+ty7u1iGM6BVl5Ykh1QIQ/ZN6Oeq8va1QniG9Prf4oH/DCWzaiGjetLzNxOTCAFg90p98rEPIaLSJLoQ7pZa3PvL03CqW4oOMilklKZv2cjeCbfbRxxdjGlZfDQOsgPTSINFx4AnXjn4hwmHEZJkR6+3Kf806ihaFJOfOHntHuoz8EYIfCuhrddkBUCyk3DhwJCUDgZR9z0HsCRHRW08LhCFVfeV3Nv2/JPk3QIyANkNT7holvhTNAAqwpmJgKikYnwMtHBEiXZnsDDG0o9BEYCTrfcJ6kyEo/AKjnHT826AD0LBL/yfEp8lGeHOqN+B3+YGeFPxb4oBtf2Cr38gIr/tq6RQTepViFJkW/7UtiWETlDYTt60COPWfvCsHfn/QNpPsqjvoZayEyfhD7hslgQA=
                openai.api.key: AgAuQSckzDjdWZ9KZJ26RLVhZAwAySGXYASND2p60XJ9RBDYgnq372VpL6Hd1XVXXKNbX1eD1Lc1wZODO6lc2M/TdcUhjqE1ZHL06E69pfPm+cf9ws3D61cy5QOdX1ZNoaXCzPD4jeRzidLDV0ALdPjqu91Mc8osAp/1edqycbSNQRXeMsMTkZla8QflyR9DNXwDAQsP0cRgKGwrHZ/4hcVOwh0Wpz8pGG0mRYTkpCUxYfJvj4cU0zNFuKk5AFv5OjJobW8r7If5tMY4I0ZLwmSztfcap4KtMkvdolbfCRujb2Iaw42AvUOhJAZNBSmlpc2jbf8M7DlX05Ov7YH8d8zfGFkMj5R+DfW9+1pSrtD/qvI2Styd1JMoEkixwn164I9Ou0NZUGuwk1vSV1veZ3o8vvqWv+sfNmBT+vj35QJv8KXZLnA5xRpltJ3sIRRko/v5xQFEN7GkCK7RlTeZ+MvskQuwJp8SHoW53mMQF/x32VblwprvnwY+rw3GaDPyup4eswKLCWRpvfugh6ZXkdIndSS3WUObX4v9L3256vdWOYEo67hhJD0u4NwKvi6yQwajNm4SgwyfdFPFQqCWuWxREXckkdgOmXb9XbcvtYvbFEBnVcT5YNEaZUUcF9HwHbCeAg5My+UedBuRaCLRGCIFr6WylYX3TCGAGaHPEBRf8fkBpYrttYQ8m/Y3CeqskwBDLNlkyEEbxbx4N5f/GmP0oWKOSum3CRLs6GqQOaNv/gczM08H5COfbPqkG/EhfMbyXXQ6HW4TMef6AvkTI0n0ESqrzi0A/ldoZWMTQU+OzA1EeaGmNxiYoVltkUf0tbOPJWxdVuZ6IxwLZv9RuTbdwZ1tuiQEXiGPMJ8CFqkgAWiNtm2MKz9MtCDorw8bMzpAPfxT/kLPBXb2YF7xSyD41kAYkQ==
              template:
                metadata:
                  name: openwebui-creds
                type: Opaque
        websocket:
          enabled: true
        #   url: redis://open-webui-redis-master:6379/0
        #   redis:
        #     enabled: false
        # redis-cluster:
        #   enabled: true
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
