apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: ai
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/open-webui-6.6.0
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        image:
          tag: "0.6"
          pullPolicy: "Always"
        ollama:
          enabled: false
        pipelines:
          enabled: false
        ollamaUrls:
          - http://ollama:11434
        replicaCount: 3
        ingress:
          enabled: true
          class: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
            nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
          host: llm.app.jyje.online
          tls: true
          existingSecret: llm-letsencrypt-tls
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          size: 10Gi
          accessModes:
            - ReadWriteMany
          storageClass: longhorn
        extraEnvVars:
          - name: OPENAI_API_BASE_URL
            value: https://api.openai.com/v1
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: openai.api.key
          - name: VECTOR_DB
            value: milvus
          - name: MILVUS_URI
            valueFrom:
              secretKeyRef:
                name: openwebui-creds
                key: milvus.uri
          - name: RAG_EMBEDDING_ENGINE
            value: openai
          - name: RAG_EMBEDDING_MODEL
            value: text-embedding-3-small
          - name: SOCKET_LOG_LEVEL
            value: debug
        extraResources:
          - apiVersion: bitnami.com/v1alpha1
            kind: SealedSecret
            metadata:
              name: openwebui-creds
            spec:
              template:
                type: Opaque
                metadata:
                  name: openwebui-creds
              encryptedData:
                milvus.uri: AgAbH5D+PMVJTh4OhqTNpGDbQ8L1S7oQeckO2C6GV7aM48e3LD0mxiMkT744j9B6ybvIZHMAamBg575xfl8iCNqizpnoetjBD+8dnwhgqNV4oocHLf8mRx4jN3vvdWbYpMeg/ZHwwiqWjSFa2tsHyHGoRrSg17bwbZAoVv9PHne/2Posr0828kMOr40RYIFIEHhpNeOLLbrAqr97mFYUUIbFvBv1Vu1UUQdpZSOUJZ3VbQD7dvgyAmiUCwom/gklg7wlqXXg0HtvkTPOnjW4ZvsxoFeqUn2bJa2GtOkqiAWQA5d3zuiZ10Pvg7j2q2LaK78mIcESXcVNEiyxvcEvp3L63wi0FYfY68KWOhAbr5IdrI/2d1DS/YG2zyHhqh7EbyEnaQpnQeaafSxhG8ek4gQKR5cgKLDGgMZh+QMgB0dw2wMqs62hJmv7W4paG+N0almlCsBwUbHq2G+l+epf08SKDGIohLLv54ss/xy5Vg4ErnSbjWvl//dDtv7OJWQH4uaypbeXZo2CKqXKPm+SfMbJErE9XosXmdqsXdM8V7nz0+9d7m/7o1hvhIsTELKoLT74Pu036ofM8oz43RPH/3MnEr+i22gB6vINDA6smtFnaUgxfXCgwFT8vc4vryH0GOMJIMLAGx7dqKnuJQfta9hWGtUbqqsmhnPHY4rh5HVbEHwSukvm2E7LdoT0YRCzy/nJZVxQaIuyPpXNBz2G2L8ZDaFoD+I2VfWxo8kFh7pR8NEdtWdYHysD6ztsr0EGIkVDTmCqcYceS8dm0QcZGdaJN/cnMYyH
                openai.api.base: AgB7KoeHf32krZMo95QDfrgsxUBBbZ0egcdDmGsgyPMe+ySTVhBGe/YH238P9IHvEvocRe4zyuFgr8wvU2Bx/bU65gCbKcgKeF863Pia2pUGnn1BN3ah5AmMaZE9W4Bj9UOScKeGEz4LxFJhVEn4cHVPM+mUT0qV7Bxe0dxEowhrnC9SbOMZzGq5gU7OJFPcXmasSxENCzH8IVclyrZ2Z8w03/+xspbOBbJ6GYbgCAV6zFzbZfZDK441S546Orcgy1a5rZhcslSIbviMKDdfngbC1NMLB4MwTG/gmTfrcJIX+RXL+FCPfWlBPAfIfZ/HzmfSpIGXNgP5qJlDRrM7O26WI/KZosE9LG2ligo0cP28Usjc031gvGNRJw9vs0HLPFlIzz1t4u8ssZyxoE1yg0mvHKUTkpaFv0B9oPNx6/8RueWIhxveMRr6TkWz30Gvo0uCDmzJV4vWEsWNriLAtCDHM4rDch5VGmyj1A9FWudDhT8gt/pTQBjFnu2MxJLfWp6846HJnwA7wl6xbryHyZysTzDqbZRSkA1T0S24nXHLN8TEIt2SoDLvsZm1TyETsfEbhNdARECJEpqrtH+zcD2cTYjqZevznFLs7xlqezy++HfP4ljRcUJB0qEgkkwhy8ksB3uoBKgssu5mPjRdNJfnec5Twb6LztSXVOHA3nOiZRl5ZrodKfhpHMAb1JklYSRfW9WjBryytEvIdppg9PtFTeFkGJYYBZJn
                openai.api.key: AgCGtEtUNFwNBK8MVfMULPlnxWedYxoZkgbGvoWUrXLLBt0qGsaSJrfUDJFvb2xavIuPiEvUjr2d21lzialwxvW9PWAigzIGqXcBakIY2WtjP9cSpIbmiU6j8zVueJUCgApeQpfDOriIQ6bBNptjjFvChUTJZwBrr20tRFmMmxubnSsjI/ru1wp09WLX24MgOiLuNggN0Bm6jecwKXzOjDDSIZ2b5TzDdA07oGQ9kOTF4u6p5qx00grm6BmiqOeaE54sWlij2XkGW0f3W2bTfqqXR8jmtnOBvLpLFghNawm8ZW5kjxFTQO5UQO5xvuXls8FhUp1chQqtwt0fsLpPYcSmbJ3i/zGGFnO2Rk6zCn5wKNTJRFmXNEplNeaU1gtqdsbGmP16vWHBl9PnTJU60Vfjo5Mqr5cNx27IOhhTvlr9RuK0hFkt/+vnzYqTbdAzghVwAHFNoNPKWYUrEI7OdAOxjWSbELtbI/gkgM6iezyB+vCtlRRGgVwNdLTbbhhFI1vcuhaFmmtfzWmUZ92JGZlNtm61GtQhmv6i39vlVzz0S7UitACZRU4fN0hPDMO6ybayjBJSEE8i6zd/ys1yPw/1LQvK3Ih67BmS7fRUKUIA/R1undd1e+U3obxqQFP+dmnWqAxwXbXmMixnlDxFYckwoNq5AXji+xJ5VqKXt+tCDJ8lZNJDGXxd30psbETV4QyFbsY5iz4tNYPrIjeJyxQRczRmxbuAnVIgGp86sLN6iDeIiTPeeHbtaixD0Sz+kUuFL6nLl/sOJXLoY8O5+gHa4/LykybW+MQq9WTjNPV1RNGkoYoR1PVNwxHzYpQdwuYHTKx0QRulsm54lrrAlS9ATBJcJBzdsEwzPCDpfUXdfdJ+3rE5HvGQ6UqSqXee5SMj1e+NRnsNCa3NniAILykplL6sVw==
        websocket:
          enabled: true
        #   url: redis://open-webui-redis-master:6379/0
        #   redis:
        #     enabled: false
        # redis-cluster:
        #   enabled: true
  destination:
    namespace: ollama-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
