apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-csi-driver
  namespace: argocd
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: main
    path: helm/seaweedfs/seaweedfs-csi-driver-0.2.15
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        seaweedfsFiler: "seaweedfs-filer.seaweedfs.svc.cluster.local:8888"
        storageClassName: seaweedfs-storage
        isDefaultStorageClass: false
  destination:
    namespace: seaweedfs
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
