apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-operator
spec:
  project: base
  source:
    repoURL: https://github.com/jyje/cluster
    targetRevision: develop
    path: helm/secret-operator-v0.7.4
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        controllerManager:
          replicas: 1
  destination:
    namespace: infisical
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
