{{- if and .Values.ingress.enabled .Values.ingress.publicPaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mungchilog-public
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.publicPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: mungchilog
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}
