annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: fixed
      description: set default updateStrategy to Recreate
    - kind: added
      description: add service.loadBalancerIP
apiVersion: v2
appVersion: 0.3.12
description: Get up and running with large language models locally.
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
- ai
- llm
- llama
- mistral
kubeVersion: ^1.16.0-0
maintainers:
- email: contact@otwld.com
  name: OTWLD
name: ollama
sources:
- https://github.com/ollama/ollama
- https://github.com/otwld/ollama-helm
type: application
version: 0.61.0
